apiVersion: apps/v1
kind: Deployment
metadata:
  name: example
  annotations: { "cosign.sigstore.dev/verified": "true" }
spec:
  replicas: 1
  selector: { matchLabels: { app: example } }
  template:
    metadata: { labels: { app: example } }
    spec:
      containers:
        - name: ex
          image: ghcr.io/owner/example:sha256-deadbeef
          resources:
            limits: { cpu: "500m", memory: "256Mi" }

